parameters:
    # Paramètres spécifiques à la base de données
    database_driver: '%env(DATABASE_DRIVER)%'
    database_server_version: '%env(DATABASE_SERVER_VERSION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $databaseDriver: '%database_driver%'
            $databaseServerVersion: '%database_server_version%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailerService:
        arguments:
            $mailer: '@mailer.mailer'

    App\Repository\:
        resource: '../src/Repository/'
        tags: ['doctrine.repository_service']

