name: Deploy to Hostinger with ssh private key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Hostinger
      env:
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_USER: ${{ secrets.SSH_USER }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_DRIVER: ${{ secrets.DATABASE_DRIVER }}
        DATABASE_SERVER_VERSION: ${{ secrets.DATABASE_SERVER_VERSION }}
        EMAIL_ADMIN: ${{ secrets.EMAIL_ADMIN }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_OWNER: ${{ secrets.EMAIL_OWNER }}
        MAILER_DSN: ${{ secrets.MAILER_DSN }}
        
      run: |
        ssh -p 65002 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_SERVER "
        cd domains/sandybrown-duck-473650.hostingersite.com/public_html/server-sushi-symfony &&
        git fetch origin main &&
        git reset --hard origin/main &&
        grep -q '^APP_ENV=' .env || echo 'APP_ENV=prod' >> .env &&
        sed -i 's|^APP_SECRET=.*|APP_SECRET=$APP_SECRET|' .env &&
        sed -i 's|^DATABASE_URL=.*|DATABASE_URL='"$DATABASE_URL"'|' .env &&
        sed -i 's|^DATABASE_DRIVER=.*|DATABASE_DRIVER=\"$DATABASE_DRIVER\"|' .env &&
        sed -i 's|^DATABASE_SERVER_VERSION=.*|DATABASE_SERVER_VERSION=\"$DATABASE_SERVER_VERSION\"|' .env &&
        sed -i 's|^EMAIL_ADMIN=.*|EMAIL_ADMIN=\"$EMAIL_ADMIN\"|' .env &&
        sed -i 's|^EMAIL_FROM=.*|EMAIL_FROM=\"$EMAIL_FROM\"|' .env &&
        sed -i 's|^EMAIL_OWNER=.*|EMAIL_OWNER=\"$EMAIL_OWNER\"|' .env &&
        sed -i 's|^MAILER_DSN=.*|MAILER_DSN=\"$MAILER_DSN\"|' .env &&
        ../composer.phar install --no-dev --optimize-autoloader &&
        php bin/console cache:clear --env=prod &&
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration &&
        php bin/console asset-map:compile --env=prod
        "
