name: Deploy to Hostinger with ssh private key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "APP_ENV=prod" > .env
        echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
        echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> .env
        echo "DATABASE_DRIVER=${{ secrets.DATABASE_DRIVER }}" >> .env
        echo "DATABASE_SERVER_VERSION=${{ secrets.DATABASE_SERVER_VERSION }}" >> .env
        echo "EMAIL_ADMIN=${{ secrets.EMAIL_ADMIN }}" >> .env
        echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
        echo "EMAIL_OWNER=${{ secrets.EMAIL_OWNER }}" >> .env
        echo "MAILER_DSN=${{ secrets.MAILER_DSN }}" >> .env
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Hostinger
      env:
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        # Copier le fichier .env vers le serveur
        scp -P 65002 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null .env $SSH_USER@$SSH_SERVER:domains/sandybrown-duck-473650.hostingersite.com/public_html/server-sushi-symfony/.env

        # Exécuter les commandes de déploiement sur le serveur
        ssh -p 65002 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_SERVER "
        cd domains/sandybrown-duck-473650.hostingersite.com/public_html/server-sushi-symfony &&
        git fetch origin main &&
        git reset --hard origin/main &&
        ../composer.phar install --no-dev --optimize-autoloader &&
        php bin/console cache:clear --env=prod &&
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration &&
        php bin/console asset-map:compile --env=prod
        "
